[package]
name = "back_to_sequences"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.3", features = ["derive","cargo"] }
which = "4.0.2"
glob = "0.3.0"
fxread = "0.2"

